### ISSUE TITLE
Why is it eagerly evaluating args in R <= 3.4?

### ISSUE THREAD

**Issue by DavisVaughan** [DavisVaughan/standardize#1]
https://github.com/DavisVaughan/standardize/runs/657639894#step:10:149

**Comment by krlmlr** [comment]
Does it help if the caller uses `maybe_missing(i)` ?

**Comment by DavisVaughan** [comment]
I figured it out. On R <= 3.4.4, missing dots are not directly represented as `R_MissingValue`, but are instead a promise with `PRCODE()` equal to `R_MissingValue`.
90a929fb0e822653731e69c5307ee97d07f54bca
